export const AUTHENTICATE = "AUTHENTICATE";
export type AUTHENTICATE = typeof AUTHENTICATE;

export const UNAUTHENTICATE = "UNAUTHENTICATE";
export type UNAUTHENTICATE = typeof UNAUTHENTICATE;

export const AUTHENTICATEADMIN = "AUTHENTICATEADMIN";
export type AUTHENTICATEADMIN = typeof AUTHENTICATEADMIN;
