export const AUTHENTICATE = "AUTHENTICATE";
export type AUTHENTICATETYPE = typeof AUTHENTICATE;

export const UNAUTHENTICATE = "UNAUTHENTICATE";
export type UNAUTHENTICATETYPE = typeof UNAUTHENTICATE;

export const AUTHENTICATEADMIN = "AUTHENTICATEADMIN";
export type AUTHENTICATEADMINTYPE = typeof AUTHENTICATEADMIN;
